---
- name: tap Homebrew repogitories
  homebrew_tap:
    name: "{{ item }}"
  with_items: "{{ homebrew_taps }}"

- name: update Homebrew
  homebrew:
    update_homebrew: yes

- name: install Homebrew packages
  homebrew:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('latest') }}"
    install_options: "{{
      item.install_options | default() | join(',')
      if item.install_options is not string
      else item.install_options }}"
  with_items: "{{ homebrew_packages }}"
